#Change checkpoint and sense_map path
checkpoint_dir: /feynman/home/dap/lcs/hl285110/work/Models/kappaTNG/mmgan/checkpoints/ # Where model will save checkpoints
data_path: # Path to simulation dataset
cosmo_dir_path: /feynman/home/dap/lcs/hl285110/Documents/Code/rcGAN/mass_map_utils/cosmos/
save_path: /feynman/home/dap/lcs/hl285110/work/Models/kappaTNG/mmgan/results/ # where figures and samples will be saved
fig_path: /feynman/home/dap/lcs/hl285110/work/Models/kappaTNG/mmgan/plots/

# Define the experience
experience: mass_mapping_from_hdf5
kappa_mean: 0.00015744006243248638 # Value calculated during preprocessing
kappa_std: 0.02968584954283938 # Value calculated during preprocessing

# Number of code vectors for each phase
num_z_test: 32
num_z_valid: 8
num_z_train: 2

# Data
in_chans: 4  # Real+Imag parts from observation + Kaiser squires map
out_chans: 1 # A real convergence map
im_size: 384 # Pixel width/height (square iamges)

# Optimizer:
lr: 0.001
beta_1: 0
beta_2: 0.99

# Loss weights
gp_weight: 10
adv_weight: 1e-5

# Training
batch_size: 9
num_epochs: 100
psnr_gain_tol: 0.25

num_workers: 8

# Custom config
path_to_train_val_dataset: /feynman/home/dap/lcs/hl285110/work/Data/kappaTNG_augmented/LP002_augmented_384.hdf5
path_to_std_noise: /feynman/home/dap/lcs/hl285110/work/Data/COSMOS/std_noise_384.pt
path_to_mask: /feynman/home/dap/lcs/hl285110/work/Data/COSMOS/mask_384.pt
nimgs_train: 70560
nimgs_val: 1440
